module.exports = (schema) => {
/**

------ DO NOT EDIT THIS FILE ------
  create a migration file instead

*/
return `
/** TABLE: Role */
INSERT INTO myapp.role (id,name) VALUES
(1,'ADMIN'),
(2,'MANAGER'),
(3,'USER');

INSERT INTO myapp.user (id,username,password,email,created_at,updated_at) VALUES
(1,'admin','admin','admin@admin.com',now(),now());

INSERT INTO myapp.userroles (user_id,role_id) VALUES (1,1);
`;
};
